import { useEffect, useState } from 'react';
import {
  FileText,
  DollarSign,
  Users,
  Star,
  GalleryHorizontalEnd,
  Calendar,
  ArrowLeft,
  Smartphone,
  Check,
  ChevronRight,
  TrendingUp,
  Lightbulb,
  RefreshCw,
  Send,
  Clock,
  AlertCircle,
} from 'lucide-react';
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from 'recharts';
import Badge from '@/components/Common/Badge';
import DataCard from '@/components/Common/DataCard';
import { get, post } from '@/utils/request';
import { cn } from '@/lib/utils';

interface MonthlyReportData {
  id: string;
  month: string;
  generatedAt: string;
  pushedToPhone: boolean;
  pushedAt?: string;
  autoGenerated?: boolean;
  revenue: {
    total: number;
    ticketCount: number;
    avgPrice: number;
    changePercent: number;
  };
  visitors: {
    total: number;
    changePercent: number;
  };
  exhibitions: Array<{
    id: string;
    title: string;
    visitorCount: number;
    targetVisitorCount: number;
    revenue: number;
  }>;
  topExhibits: Array<{
    id: string;
    name: string;
    category: string;
    heatScore: number;
  }>;
  conservation: {
    totalInspections: number;
    completedInspections: number;
    pendingWorkOrders: number;
    activeWorkOrders: number;
    completedWorkOrders: number;
  };
  security: {
    totalAlerts: number;
    unresolvedAlerts: number;
    avgDensity: number;
    criticalCount: number;
  };
  satisfaction: number;
}

interface ReportSummary {
  month: string;
  generatedAt: string;
  revenue: number;
  visitors: number;
  satisfaction: number;
  exhibitions: number;
}

function formatCurrency(value: number) {
  return `¥${value.toLocaleString('zh-CN')}`;
}

function formatDateTime(isoStr?: string) {
  if (!isoStr) return '-';
  const d = new Date(isoStr);
  return d.toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function generateMockReports(): ReportSummary[] {
  return [
    {
      month: '2026年4月',
      generatedAt: '2026-05-01 09:00:00',
      revenue: 114280,
      visitors: 2105,
      satisfaction: 4.3,
      exhibitions: 3,
    },
    {
      month: '2026年3月',
      generatedAt: '2026-04-01 09:00:00',
      revenue: 98650,
      visitors: 1820,
      satisfaction: 4.5,
      exhibitions: 3,
    },
    {
      month: '2026年2月',
      generatedAt: '2026-03-01 09:00:00',
      revenue: 85200,
      visitors: 1580,
      satisfaction: 4.2,
      exhibitions: 2,
    },
    {
      month: '2026年1月',
      generatedAt: '2026-02-01 09:00:00',
      revenue: 76800,
      visitors: 1420,
      satisfaction: 4.4,
      exhibitions: 2,
    },
  ];
}

function generateDailyTrend() {
  const data = [];
  for (let i = 1; i <= 30; i++) {
    data.push({
      day: `${i}日`,
      revenue: 3000 + Math.round(Math.sin(i / 3) * 1500) + Math.floor(Math.random() * 1000),
      visitors: 60 + Math.round(Math.sin(i / 4) * 30) + Math.floor(Math.random() * 20),
    });
  }
  return data;
}

const PIE_COLORS = ['#B8860B', '#8B6341', '#A68154', '#DCB03C', '#6B4A31'];

const visitorTypeData = [
  { name: '成人', value: 58 },
  { name: '学生', value: 22 },
  { name: '老人', value: 12 },
  { name: '儿童', value: 8 },
];

export default function Reports() {
  const [mockReports] = useState<ReportSummary[]>(generateMockReports());
  const [currentMonthReport, setCurrentMonthReport] = useState<MonthlyReportData | null>(null);
  const [selectedReport, setSelectedReport] = useState<MonthlyReportData | null>(null);
  const [dailyTrend] = useState(generateDailyTrend());
  const [pushing, setPushing] = useState(false);
  const [pushSuccess, setPushSuccess] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [generateSuccess, setGenerateSuccess] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const suggestions = [
    '本月客流增长显著，建议在周末高峰期增加临时工作人员和引导标识',
    '特展"华夏文明五千年"表现优异，建议延长展期或策划类似主题特展',
    '第三展厅满意度略低，建议检查设施设备并优化参观动线',
    '建议增加亲子互动项目，吸引更多家庭观众',
    '学生票占比提升，可考虑与周边学校合作推出研学套餐',
  ];

  const fetchCurrentReport = async () => {
    setLoading(true);
    setErrorMsg(null);
    try {
      const data = await get<MonthlyReportData>('/analytics/monthly-report');
      setCurrentMonthReport(data);
    } catch (e) {
      setErrorMsg('获取月度报告失败');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCurrentReport();
  }, []);

  const handleViewCurrent = () => {
    if (currentMonthReport) {
      setSelectedReport(currentMonthReport);
    }
  };

  const handleGenerateReport = async () => {
    setGenerating(true);
    setGenerateSuccess(false);
    setErrorMsg(null);
    try {
      const data = await post<MonthlyReportData>('/analytics/monthly-report/generate');
      setCurrentMonthReport(data);
      setGenerateSuccess(true);
      setTimeout(() => setGenerateSuccess(false), 3000);
    } catch (e) {
      setErrorMsg('生成月度报告失败，请稍后重试');
    } finally {
      setGenerating(false);
    }
  };

  const handlePushToMobile = async () => {
    setPushing(true);
    setPushSuccess(false);
    setErrorMsg(null);
    try {
      const res = await post<{ pushed: boolean; pushedAt: string; message: string }>(
        '/analytics/monthly-report/push-to-phone'
      );
      if (res && currentMonthReport) {
        setCurrentMonthReport({
          ...currentMonthReport,
          pushedToPhone: true,
          pushedAt: res.pushedAt,
        });
        if (selectedReport) {
          setSelectedReport({
            ...selectedReport,
            pushedToPhone: true,
            pushedAt: res.pushedAt,
          });
        }
      }
      setPushSuccess(true);
      setTimeout(() => setPushSuccess(false), 3000);
    } catch (e) {
      setErrorMsg('推送失败，请先生成月度报告');
      setTimeout(() => setErrorMsg(null), 3000);
    } finally {
      setPushing(false);
    }
  };

  if (selectedReport) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-3 flex-wrap">
            <button
              onClick={() => setSelectedReport(null)}
              className="flex items-center gap-1 rounded-lg border border-museum-brown-200 px-3 py-1.5 text-sm text-museum-brown-600 transition-colors hover:bg-museum-cream"
            >
              <ArrowLeft className="h-4 w-4" />
              返回列表
            </button>
            <h1 className="text-2xl font-bold font-serif text-museum-brown-900">
              {selectedReport.month}华夏博物馆运营报告
            </h1>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleGenerateReport}
              disabled={generating}
              className={cn(
                'flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-all border',
                generateSuccess
                  ? 'bg-museum-jade/10 border-museum-jade text-museum-jade'
                  : 'border-museum-brown-200 text-museum-brown-600 hover:bg-museum-cream'
              )}
            >
              {generateSuccess ? (
                <>
                  <Check className="h-4 w-4" />
                  已生成
                </>
              ) : generating ? (
                <>
                  <RefreshCw className="h-4 w-4 animate-spin" />
                  生成中...
                </>
              ) : (
                <>
                  <RefreshCw className="h-4 w-4" />
                  重新生成
                </>
              )}
            </button>
            <button
              onClick={handlePushToMobile}
              disabled={pushing}
              className={cn(
                'flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-all',
                pushSuccess
                  ? 'bg-museum-jade text-white'
                  : selectedReport.pushedToPhone
                  ? 'bg-museum-brown-100 text-museum-brown-500 cursor-not-allowed'
                  : 'bg-museum-gold-500 text-white hover:bg-museum-gold-600 shadow-gold hover:shadow-gold-hover'
              )}
            >
              {pushSuccess ? (
                <>
                  <Check className="h-4 w-4" />
                  推送成功
                </>
              ) : selectedReport.pushedToPhone ? (
                <>
                  <Check className="h-4 w-4" />
                  已推送
                </>
              ) : pushing ? (
                <>
                  <Smartphone className="h-4 w-4 animate-pulse" />
                  推送中...
                </>
              ) : (
                <>
                  <Smartphone className="h-4 w-4" />
                  推送到手机
                </>
              )}
            </button>
          </div>
        </div>

        <div className="rounded-xl border border-museum-gold-200 bg-gradient-to-r from-museum-gold-50 to-museum-cream p-5">
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-3">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-museum-gold-100 text-museum-gold-600">
                <FileText className="h-6 w-6" />
              </div>
              <div>
                <h2 className="font-semibold text-museum-brown-800">月度运营报告</h2>
                <div className="mt-1 flex items-center gap-4 flex-wrap text-sm text-museum-brown-500">
                  <span className="flex items-center gap-1">
                    <Clock className="h-3.5 w-3.5" />
                    生成时间：{formatDateTime(selectedReport.generatedAt)}
                  </span>
                  {selectedReport.pushedToPhone && (
                    <span className="flex items-center gap-1 text-museum-jade">
                      <Send className="h-3.5 w-3.5" />
                      已推送：{formatDateTime(selectedReport.pushedAt)}
                    </span>
                  )}
                </div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {selectedReport.autoGenerated ? (
                <Badge variant="gold">系统自动生成</Badge>
              ) : (
                <Badge variant="brown">手动生成</Badge>
              )}
            </div>
          </div>
        </div>

        {errorMsg && (
          <div className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            <AlertCircle className="h-4 w-4 flex-shrink-0" />
            {errorMsg}
          </div>
        )}

        <div>
          <h3 className="mb-3 text-lg font-semibold text-museum-brown-800">月度核心指标总览</h3>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
            <DataCard
              title="月度总收入"
              value={formatCurrency(selectedReport.revenue.total)}
              subtitle={`${selectedReport.revenue.ticketCount} 张门票 · 均价 ${formatCurrency(selectedReport.revenue.avgPrice)}`}
              trend={selectedReport.revenue.changePercent}
              icon={<DollarSign className="h-6 w-6" />}
              color="gold"
            />
            <DataCard
              title="月度总客流"
              value={selectedReport.visitors.total.toLocaleString()}
              subtitle="参观人次"
              trend={selectedReport.visitors.changePercent}
              icon={<Users className="h-6 w-6" />}
              color="brown"
            />
            <DataCard
              title="举办展览数"
              value={selectedReport.exhibitions.length}
              subtitle="在展展览"
              icon={<GalleryHorizontalEnd className="h-6 w-6" />}
              color="jade"
            />
            <DataCard
              title="平均满意度"
              value={selectedReport.satisfaction.toFixed(1)}
              subtitle="基于访客评分"
              icon={<Star className="h-6 w-6" />}
              color="crimson"
            />
          </div>
        </div>

        <div className="grid grid-cols-1 gap-5 lg:grid-cols-3">
          <div className="rounded-xl border border-museum-brown-100 bg-white p-5 shadow-museum lg:col-span-2">
            <h3 className="mb-4 font-semibold text-museum-brown-800">月度收入与客流趋势</h3>
            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={dailyTrend}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#E8DCC8" />
                  <XAxis dataKey="day" tick={{ fontSize: 11, fill: '#8B6341' }} axisLine={{ stroke: '#E8DCC8' }} />
                  <YAxis yAxisId="left" tick={{ fontSize: 11, fill: '#8B6341' }} axisLine={{ stroke: '#E8DCC8' }} />
                  <YAxis yAxisId="right" orientation="right" tick={{ fontSize: 11, fill: '#8B6341' }} axisLine={{ stroke: '#E8DCC8' }} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#FDF8F3',
                      border: '1px solid #E8DCC8',
                      borderRadius: '8px',
                    }}
                  />
                  <Legend />
                  <Line yAxisId="left" type="monotone" dataKey="revenue" name="收入(元)" stroke="#B8860B" strokeWidth={2.5} dot={false} />
                  <Line yAxisId="right" type="monotone" dataKey="visitors" name="客流(人)" stroke="#6B4A31" strokeWidth={2} dot={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="rounded-xl border border-museum-brown-100 bg-white p-5 shadow-museum">
            <h3 className="mb-4 font-semibold text-museum-brown-800">观众类型分布</h3>
            <div className="h-56">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={visitorTypeData}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    paddingAngle={3}
                    dataKey="value"
                  >
                    {visitorTypeData.map((_, index) => (
                      <Cell key={`cell-${index}`} fill={PIE_COLORS[index % PIE_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#FDF8F3',
                      border: '1px solid #E8DCC8',
                      borderRadius: '8px',
                    }}
                    formatter={(value: number) => [`${value}%`, '占比']}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="mt-3 grid grid-cols-2 gap-2">
              {visitorTypeData.map((item, index) => (
                <div key={item.name} className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full" style={{ backgroundColor: PIE_COLORS[index] }} />
                  <span className="text-xs text-museum-brown-600">
                    {item.name} {item.value}%
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-museum-brown-100 bg-white p-5 shadow-museum">
          <h3 className="mb-4 font-semibold text-museum-brown-800">各展览运营数据</h3>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-museum-brown-100 text-left text-museum-brown-500">
                  <th className="pb-3 font-medium">展览名称</th>
                  <th className="pb-3 font-medium">目标参观</th>
                  <th className="pb-3 font-medium">实际参观</th>
                  <th className="pb-3 font-medium">收入</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-museum-brown-50">
                {selectedReport.exhibitions.map((ex) => (
                  <tr key={ex.id} className="transition-colors hover:bg-museum-cream/30">
                    <td className="py-3 font-medium text-museum-brown-800">{ex.title}</td>
                    <td className="py-3 text-museum-brown-600">{ex.targetVisitorCount.toLocaleString()}</td>
                    <td className="py-3 text-museum-brown-600">{ex.visitorCount.toLocaleString()}</td>
                    <td className="py-3 font-medium text-museum-gold-700">{formatCurrency(ex.revenue)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
          <div className="rounded-xl border border-museum-brown-100 bg-white p-5 shadow-museum">
            <h3 className="mb-4 font-semibold text-museum-brown-800">文物保护数据</h3>
            <div className="h-56">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  data={[
                    { name: '巡检总数', value: selectedReport.conservation.totalInspections },
                    { name: '已完成巡检', value: selectedReport.conservation.completedInspections },
                    { name: '待审批工单', value: selectedReport.conservation.pendingWorkOrders },
                    { name: '进行中工单', value: selectedReport.conservation.activeWorkOrders },
                    { name: '已完成工单', value: selectedReport.conservation.completedWorkOrders },
                  ]}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#E8DCC8" />
                  <XAxis dataKey="name" tick={{ fontSize: 11, fill: '#8B6341' }} axisLine={{ stroke: '#E8DCC8' }} />
                  <YAxis tick={{ fontSize: 11, fill: '#8B6341' }} axisLine={{ stroke: '#E8DCC8' }} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#FDF8F3',
                      border: '1px solid #E8DCC8',
                      borderRadius: '8px',
                    }}
                  />
                  <Bar dataKey="value" fill="#B8860B" radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="rounded-xl border border-museum-brown-100 bg-white p-5 shadow-museum">
            <h3 className="mb-4 font-semibold text-museum-brown-800">热门展品 TOP 5</h3>
            <div className="space-y-3">
              {selectedReport.topExhibits.map((ex, idx) => (
                <div key={ex.id} className="flex items-center gap-3">
                  <div
                    className={cn(
                      'flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg text-sm font-bold',
                      idx === 0
                        ? 'bg-museum-gold-500 text-white'
                        : idx < 3
                        ? 'bg-museum-gold-200 text-museum-gold-700'
                        : 'bg-museum-brown-100 text-museum-brown-600'
                    )}
                  >
                    {idx + 1}
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="truncate font-medium text-museum-brown-800">{ex.name}</p>
                    <p className="text-xs text-museum-brown-500">
                      {ex.category} · 热度 {ex.heatScore}
                    </p>
                  </div>
                  <div className="h-2 w-24 overflow-hidden rounded-full bg-museum-brown-100">
                    <div
                      className="h-full rounded-full bg-gradient-to-r from-museum-gold-400 to-museum-gold-600"
                      style={{ width: `${ex.heatScore}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-museum-brown-100 bg-white p-5 shadow-museum">
          <div className="mb-4 flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-museum-gold-600" />
            <h3 className="font-semibold text-museum-brown-800">系统运营建议</h3>
          </div>
          <div className="space-y-3">
            {suggestions.map((suggestion, index) => (
              <div
                key={index}
                className="flex items-start gap-3 rounded-lg bg-museum-cream/40 p-3"
              >
                <div className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-museum-gold-100 text-xs font-bold text-museum-gold-700">
                  {index + 1}
                </div>
                <p className="text-sm text-museum-brown-700">{suggestion}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold font-serif text-museum-brown-900">
            运营报告
          </h1>
          <p className="mt-1 text-sm text-museum-brown-500">
            每月1日自动生成，全维度分析博物馆运营状况
            {currentMonthReport && (
              <span className="ml-2 text-museum-jade flex items-center inline-flex gap-1">
                <Clock className="inline h-3.5 w-3.5" />
                本月报告生成时间：{formatDateTime(currentMonthReport.generatedAt)}
              </span>
            )}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleGenerateReport}
            disabled={generating}
            className={cn(
              'flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-medium transition-all',
              generateSuccess
                ? 'border-museum-jade bg-museum-jade/10 text-museum-jade'
                : 'border-museum-brown-200 text-museum-brown-700 hover:bg-museum-cream'
            )}
          >
            {generateSuccess ? (
              <>
                <Check className="h-4 w-4" />
                已生成
              </>
            ) : generating ? (
              <>
                <RefreshCw className="h-4 w-4 animate-spin" />
                生成中...
              </>
            ) : (
              <>
                <RefreshCw className="h-4 w-4" />
                生成月度报告
              </>
            )}
          </button>
          {currentMonthReport && (
            <button
              onClick={handlePushToMobile}
              disabled={pushing}
              className={cn(
                'flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-all',
                pushSuccess
                  ? 'bg-museum-jade text-white'
                  : currentMonthReport.pushedToPhone
                  ? 'bg-museum-brown-100 text-museum-brown-500 cursor-not-allowed'
                  : 'bg-museum-gold-500 text-white hover:bg-museum-gold-600 shadow-gold hover:shadow-gold-hover'
              )}
            >
              {pushSuccess ? (
                <>
                  <Check className="h-4 w-4" />
                  推送成功
                </>
              ) : currentMonthReport.pushedToPhone ? (
                <>
                  <Check className="h-4 w-4" />
                  已推送到手机
                </>
              ) : pushing ? (
                <>
                  <Smartphone className="h-4 w-4 animate-pulse" />
                  推送中...
                </>
              ) : (
                <>
                  <Smartphone className="h-4 w-4" />
                  推送到手机
                </>
              )}
            </button>
          )}
        </div>
      </div>

      {errorMsg && (
        <div className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          <AlertCircle className="h-4 w-4 flex-shrink-0" />
          {errorMsg}
        </div>
      )}

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <div className="text-museum-brown-500">加载中...</div>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {currentMonthReport && (
            <div
              onClick={handleViewCurrent}
              className="cursor-pointer rounded-xl border border-museum-gold-300 bg-white p-5 shadow-museum transition-all hover:shadow-museum-hover ring-2 ring-museum-gold-200"
            >
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-museum-gold-100 text-museum-gold-600">
                    <FileText className="h-6 w-6" />
                  </div>
                  <div>
                    <h3 className="font-bold text-museum-brown-900">{currentMonthReport.month}</h3>
                    <div className="mt-1 flex items-center gap-1 text-xs text-museum-brown-400">
                      <Calendar className="h-3 w-3" />
                      {formatDateTime(currentMonthReport.generatedAt)}
                    </div>
                  </div>
                </div>
                <div className="flex flex-col items-end gap-1">
                  <Badge variant="gold">最新</Badge>
                  {currentMonthReport.pushedToPhone && (
                    <Badge variant="success">已推送</Badge>
                  )}
                </div>
              </div>

              <div className="mt-4 grid grid-cols-2 gap-3">
                <div className="rounded-lg bg-museum-cream/50 p-3">
                  <p className="text-xs text-museum-brown-400">总收入</p>
                  <p className="mt-0.5 text-lg font-bold text-museum-gold-700">
                    {formatCurrency(currentMonthReport.revenue.total)}
                  </p>
                </div>
                <div className="rounded-lg bg-museum-cream/50 p-3">
                  <p className="text-xs text-museum-brown-400">总客流</p>
                  <p className="mt-0.5 text-lg font-bold text-museum-brown-700">
                    {currentMonthReport.visitors.total.toLocaleString()}
                  </p>
                </div>
                <div className="rounded-lg bg-museum-cream/50 p-3">
                  <p className="text-xs text-museum-brown-400">满意度</p>
                  <p className="mt-0.5 text-lg font-bold text-museum-crimson">
                    {currentMonthReport.satisfaction.toFixed(1)}
                    <span className="text-xs font-normal">/5.0</span>
                  </p>
                </div>
                <div className="rounded-lg bg-museum-cream/50 p-3">
                  <p className="text-xs text-museum-brown-400">展览数</p>
                  <p className="mt-0.5 text-lg font-bold text-museum-jade">
                    {currentMonthReport.exhibitions.length}
                  </p>
                </div>
              </div>

              <div className="mt-4 flex items-center justify-between border-t border-museum-brown-100 pt-3">
                <span className="text-sm text-museum-gold-600">查看详情</span>
                <ChevronRight className="h-4 w-4 text-museum-gold-600" />
              </div>
            </div>
          )}

          {mockReports.map((report) => (
            <div
              key={report.month}
              className="rounded-xl border border-museum-brown-100 bg-white p-5 shadow-museum opacity-60"
            >
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-museum-brown-100 text-museum-brown-500">
                    <FileText className="h-6 w-6" />
                  </div>
                  <div>
                    <h3 className="font-bold text-museum-brown-900">{report.month}</h3>
                    <div className="mt-1 flex items-center gap-1 text-xs text-museum-brown-400">
                      <Calendar className="h-3 w-3" />
                      {report.generatedAt}
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-4 grid grid-cols-2 gap-3">
                <div className="rounded-lg bg-museum-cream/50 p-3">
                  <p className="text-xs text-museum-brown-400">总收入</p>
                  <p className="mt-0.5 text-lg font-bold text-museum-gold-700">
                    {formatCurrency(report.revenue)}
                  </p>
                </div>
                <div className="rounded-lg bg-museum-cream/50 p-3">
                  <p className="text-xs text-museum-brown-400">总客流</p>
                  <p className="mt-0.5 text-lg font-bold text-museum-brown-700">
                    {report.visitors.toLocaleString()}
                  </p>
                </div>
                <div className="rounded-lg bg-museum-cream/50 p-3">
                  <p className="text-xs text-museum-brown-400">满意度</p>
                  <p className="mt-0.5 text-lg font-bold text-museum-crimson">
                    {report.satisfaction}
                    <span className="text-xs font-normal">/5.0</span>
                  </p>
                </div>
                <div className="rounded-lg bg-museum-cream/50 p-3">
                  <p className="text-xs text-museum-brown-400">展览数</p>
                  <p className="mt-0.5 text-lg font-bold text-museum-jade">
                    {report.exhibitions}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
