import { Router, type Request, type Response } from 'express';
import {
  inspections,
  maintenancePlans,
  workOrders,
  messages,
  exhibits,
  users,
} from '../data/mockData.js';
import type { WorkOrder, Message, Inspection } from '../../shared/types.js';

const router = Router();

router.get('/inspections/today', async (req: Request, res: Response): Promise<void> => {
  const { inspectorId } = req.query;
  const today = new Date().toISOString().split('T')[0];

  let tasks = inspections.filter((t: Inspection) => t.scheduledDate === today);

  if (inspectorId) {
    tasks = tasks.filter((t: Inspection) => t.inspectorId === inspectorId);
  }

  res.json({
    success: true,
    data: tasks,
  });
});

interface SubmitInspectionRequest {
  items: { id: string; name: string; description: string; status: 'normal' | 'abnormal' | 'unchecked'; remark?: string }[];
  remark?: string;
}

router.post('/inspections/:id/submit', async (req: Request, res: Response): Promise<void> => {
  const { id } = req.params;
  const { items, remark }: SubmitInspectionRequest = req.body;

  const task = inspections.find((t: Inspection) => t.id === id);

  if (!task) {
    res.status(404).json({
      success: false,
      error: '巡检任务不存在',
    });
    return;
  }

  if (!items) {
    res.status(400).json({
      success: false,
      error: '缺少必要参数',
    });
    return;
  }

  task.items = items;
  task.status = 'completed';
  task.completedAt = new Date().toISOString();
  if (remark) {
    task.remark = remark;
  }

  res.json({
    success: true,
    data: task,
  });
});

function getMaintenanceFrequencyByCategory(category: string): 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly' {
  const categoryMap: Record<string, 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly'> = {
    painting: 'daily',
    ceramic: 'weekly',
    jade: 'weekly',
    bronze: 'monthly',
    other: 'monthly',
  };
  return categoryMap[category] || 'monthly';
}

function getDaysByFrequency(freq: string): number {
  const freqMap: Record<string, number> = {
    daily: 1,
    weekly: 7,
    monthly: 30,
    quarterly: 90,
    yearly: 365,
  };
  return freqMap[freq] || 30;
}

router.get('/maintenance/plans', async (_req: Request, res: Response): Promise<void> => {
  const autoPlans = exhibits
    .map((exhibit) => {
      const frequency = getMaintenanceFrequencyByCategory(exhibit.category);
      const lastDate = new Date(exhibit.lastInspectionDate);
      const daysToAdd = getDaysByFrequency(frequency);
      lastDate.setDate(lastDate.getDate() + daysToAdd);
      const scheduledDate = lastDate.toISOString().split('T')[0];

      return {
        id: 'auto-' + exhibit.id,
        exhibitId: exhibit.id,
        exhibitName: exhibit.name,
        exhibitCategory: exhibit.category,
        type: 'cleaning' as const,
        scheduledDate,
        frequency,
        description: `${exhibit.name} 定期维护保养`,
        status: scheduledDate <= new Date().toISOString().split('T')[0] ? 'pending' : 'upcoming',
      };
    });

  const existingPlans = maintenancePlans.map((p) => {
    const exhibit = exhibits.find((e) => e.id === p.exhibitId);
    return {
      ...p,
      exhibitName: exhibit?.name || '',
      exhibitCategory: exhibit?.category || '',
    };
  });

  res.json({
    success: true,
    data: {
      autoGenerated: autoPlans,
      existing: existingPlans,
    },
  });
});

router.get('/workorders', async (_req: Request, res: Response): Promise<void> => {
  const list = workOrders
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .map((w) => {
      const exhibit = exhibits.find((e) => e.id === w.exhibitId);
      const requester = users.find((u) => u.id === w.requesterId);
      const assignee = w.assigneeId ? users.find((u) => u.id === w.assigneeId) : null;
      return {
        ...w,
        exhibitName: exhibit?.name || '',
        requesterName: requester?.name || '',
        assigneeName: assignee?.name || null,
      };
    });

  res.json({
    success: true,
    data: list,
  });
});

interface CreateWorkOrderRequest {
  title: string;
  description: string;
  type: 'maintenance' | 'repair' | 'installation' | 'inspection' | 'other';
  priority: 'low' | 'medium' | 'high' | 'critical';
  requesterId: string;
  hallId?: string;
  exhibitId?: string;
}

router.post('/workorders', async (req: Request, res: Response): Promise<void> => {
  const {
    title,
    description,
    type,
    priority,
    requesterId,
    hallId,
    exhibitId,
  }: CreateWorkOrderRequest = req.body;

  if (!title || !description || !type || !priority || !requesterId) {
    res.status(400).json({
      success: false,
      error: '缺少必要参数',
    });
    return;
  }

  const requester = users.find((u) => u.id === requesterId);
  const curators = users.filter((u) => u.role === 'curator');
  const hall = hallId ? exhibits.find((e) => e.hallId === hallId) : null;

  const newWorkOrder: WorkOrder = {
    id: 'wo-' + (workOrders.length + 1),
    title,
    description,
    type,
    priority,
    status: 'pending_approval',
    requesterId,
    requesterName: requester?.name || '',
    assigneeId: curators.length > 0 ? curators[0].id : undefined,
    assigneeName: curators.length > 0 ? curators[0].name : undefined,
    hallId,
    hallName: hall?.location,
    exhibitId,
    exhibitName: exhibitId ? exhibits.find((e) => e.id === exhibitId)?.name : undefined,
    createdAt: new Date().toISOString(),
  };

  workOrders.push(newWorkOrder);

  const exhibit = exhibitId ? exhibits.find((e) => e.id === exhibitId) : null;
  curators.forEach((curator) => {
    const newMessage: Message = {
      id: 'msg-' + (messages.length + 1),
      type: 'approval',
      title: '新工单待审批',
      content: `文物「${exhibit?.name || ''}」有新的工单需要您审批：${title}`,
      senderId: requesterId,
      senderName: requester?.name || '',
      receiverId: curator.id,
      receiverName: curator.name,
      read: false,
      createdAt: new Date().toISOString(),
      relatedType: 'work_order',
      relatedId: newWorkOrder.id,
      priority: 'high',
    };
    messages.push(newMessage);
  });

  res.json({
    success: true,
    data: newWorkOrder,
  });
});

router.put('/workorders/:id/approve', async (req: Request, res: Response): Promise<void> => {
  const { id } = req.params;
  const { assigneeId } = req.body as { assigneeId?: string };

  const workOrder = workOrders.find((w) => w.id === id);

  if (!workOrder) {
    res.status(404).json({
      success: false,
      error: '工单不存在',
    });
    return;
  }

  workOrder.status = 'approved';
  if (assigneeId) {
    workOrder.assigneeId = assigneeId;
    const assignee = users.find((u) => u.id === assigneeId);
    workOrder.assigneeName = assignee?.name;
  }
  workOrder.approvedAt = new Date().toISOString();

  const exhibit = workOrder.exhibitId ? exhibits.find((e) => e.id === workOrder.exhibitId) : null;
  const requester = users.find((u) => u.id === workOrder.requesterId);
  if (requester) {
    const newMessage: Message = {
      id: 'msg-' + (messages.length + 1),
      type: 'notification',
      title: '工单已通过审批',
      content: `您提交的关于「${exhibit?.name || ''}」的工单「${workOrder.title}」已通过审批，可以开始执行。`,
      senderId: workOrder.assigneeId || 'system',
      senderName: workOrder.assigneeName || '系统',
      receiverId: requester.id,
      receiverName: requester.name,
      read: false,
      createdAt: new Date().toISOString(),
      relatedType: 'work_order',
      relatedId: workOrder.id,
      priority: 'medium',
    };
    messages.push(newMessage);
  }

  res.json({
    success: true,
    data: workOrder,
  });
});

interface RejectRequest {
  assigneeId?: string;
  reason: string;
}

router.put('/workorders/:id/reject', async (req: Request, res: Response): Promise<void> => {
  const { id } = req.params;
  const { assigneeId, reason }: RejectRequest = req.body;

  if (!reason) {
    res.status(400).json({
      success: false,
      error: '请提供驳回原因',
    });
    return;
  }

  const workOrder = workOrders.find((w) => w.id === id);

  if (!workOrder) {
    res.status(404).json({
      success: false,
      error: '工单不存在',
    });
    return;
  }

  workOrder.status = 'rejected';
  if (assigneeId) {
    workOrder.assigneeId = assigneeId;
    const assignee = users.find((u) => u.id === assigneeId);
    workOrder.assigneeName = assignee?.name;
  }
  workOrder.approvedAt = new Date().toISOString();
  workOrder.remark = reason;

  const exhibit = workOrder.exhibitId ? exhibits.find((e) => e.id === workOrder.exhibitId) : null;
  const requester = users.find((u) => u.id === workOrder.requesterId);
  if (requester) {
    const newMessage: Message = {
      id: 'msg-' + (messages.length + 1),
      type: 'notification',
      title: '工单被驳回',
      content: `您提交的关于「${exhibit?.name || ''}」的工单「${workOrder.title}」被驳回，原因：${reason}`,
      senderId: workOrder.assigneeId || 'system',
      senderName: workOrder.assigneeName || '系统',
      receiverId: requester.id,
      receiverName: requester.name,
      read: false,
      createdAt: new Date().toISOString(),
      relatedType: 'work_order',
      relatedId: workOrder.id,
      priority: 'high',
    };
    messages.push(newMessage);
  }

  res.json({
    success: true,
    data: workOrder,
  });
});

export default router;
